// Seed source for Supabase — not used at runtime when DATA_STORE=supabase except via seed script
import type { Job } from "./types";

export const sampleJobs: Job[] = [
  {
    id: "001",
    title: "AI Research Engineer - Computer Vision",
    titleZh: "AI研究工程师 - 计算机视觉",
    company: "Robert Bosch GmbH",
    companyZh: "博世",
    field: "ai",
    location: "Stuttgart, Germany",
    locationCode: "de",
    languageLevel: "required",
    employmentType: "full-time",
    salaryRange: "€70,000 - €95,000",
    description: "Join our AI research team to develop cutting-edge computer vision algorithms for autonomous driving and industrial automation. You will work on object detection, semantic segmentation, and sensor fusion projects with a focus on the Chinese market.",
    descriptionZh: "加入我们的AI研究团队，开发用于自动驾驶和工业自动化的前沿计算机视觉算法。您将参与目标检测、语义分割和传感器融合项目，重点关注中国市场。",
    requirements: [
      "MSc or PhD in Computer Science, Electrical Engineering, or related field",
      "Strong background in deep learning frameworks (PyTorch, TensorFlow)",
      "Experience with computer vision (OpenCV, image processing)",
      "Chinese (Mandarin) language skills for collaboration with China R&D teams",
      "German or English working proficiency",
    ],
    requirementsZh: [
      "计算机科学、电子工程或相关专业硕士或博士学位",
      "深度学习框架（PyTorch, TensorFlow）扎实基础",
      "计算机视觉经验（OpenCV, 图像处理）",
      "中文普通话能力，用于与中国研发团队协作",
      "德语或英语工作能力",
    ],
    tags: ["Computer Vision", "Deep Learning", "Autonomous Driving", "TensorFlow"],
    applicationUrl: "https://careers.bosch.com",
    postedDate: "2026-08-01",
    remoteFriendly: false,
    visaSponsorship: true,
    featured: true,
  },
  {
    id: "002",
    title: "Robotics Software Engineer",
    titleZh: "机器人软件工程师",
    company: "KUKA AG",
    companyZh: "库卡",
    field: "robotics",
    location: "Augsburg, Germany",
    locationCode: "de",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€65,000 - €85,000",
    description: "Develop motion planning and control software for industrial robot arms. Our robotics division is expanding operations in China and seeking engineers who can bridge German engineering excellence with Chinese market requirements.",
    descriptionZh: "开发工业机器人手臂的运动规划和控制软件。我们的机器人部门正在中国扩展业务，寻找能够将德国工程卓越性与中国市场需求结合起来的工程师。",
    requirements: [
      "BSc or MSc in Robotics, Mechatronics, or Computer Science",
      "Experience with ROS/ROS2, C++ programming",
      "Knowledge of motion planning algorithms",
      "Chinese language skills are a plus for China market projects",
    ],
    requirementsZh: [
      "机器人、机电一体化或计算机科学学士或硕士学位",
      "ROS/ROS2、C++编程经验",
      "运动规划算法知识",
      "中文语言能力是加分项（用于中国市场项目）",
    ],
    tags: ["ROS", "C++", "Motion Planning", "Industrial Robotics"],
    applicationUrl: "https://www.kuka.com/en-de/career",
    postedDate: "2026-07-28",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "003",
    title: "Drone Systems Engineer",
    titleZh: "无人机系统工程师",
    company: "Wingcopter GmbH",
    field: "drone",
    location: "Darmstadt, Germany",
    locationCode: "de",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€60,000 - €80,000",
    description: "Design and develop flight control systems for delivery drones. We are expanding to Asian markets including China and value team members who understand both European aviation standards and Chinese regulatory environments.",
    descriptionZh: "设计和开发送货无人机的飞行控制系统。我们正在扩展到包括中国在内的亚洲市场，希望团队成员同时了解欧洲航空标准和中国监管环境。",
    requirements: [
      "Degree in Aerospace, Electrical Engineering, or Computer Science",
      "Experience with flight control systems or embedded systems",
      "Programming skills in C/C++ and Python",
      "Knowledge of Chinese drone regulations is a plus",
    ],
    requirementsZh: [
      "航空航天、电子工程或计算机科学学位",
      "飞行控制系统或嵌入式系统经验",
      "C/C++和Python编程能力",
      "了解中国无人机法规是加分项",
    ],
    tags: ["Flight Control", "Embedded", "UAV", "Python"],
    applicationUrl: "https://wingcopter.com/careers",
    postedDate: "2026-07-25",
    remoteFriendly: true,
    visaSponsorship: true,
    featured: true,
  },
  {
    id: "004",
    title: "Full-Stack Developer (Remote, China Focus)",
    titleZh: "全栈开发工程师（远程，面向中国）",
    company: "SAP SE",
    companyZh: "SAP",
    field: "remote",
    location: "Remote (Germany-based)",
    locationCode: "remote",
    languageLevel: "fluent",
    employmentType: "full-time",
    salaryRange: "€70,000 - €90,000",
    description: "Join our cloud platform team developing solutions for the Chinese market. This remote position requires close collaboration with our Shanghai and Beijing offices. Fluent Chinese is essential for this role.",
    descriptionZh: "加入我们的云平台团队，为中国市场开发解决方案。此远程职位需要与上海和北京办公室紧密合作。流利的中文是此职位的必备条件。",
    requirements: [
      "BSc in Computer Science or equivalent experience",
      "3+ years experience with React, Node.js, and cloud platforms",
      "Fluent Chinese (Mandarin) for daily communication with China teams",
      "German or English proficiency",
      "Experience with SAP cloud solutions is a plus",
    ],
    requirementsZh: [
      "计算机科学学士或同等经验",
      "3年以上React、Node.js和云平台经验",
      "流利的中文普通话，用于与中国团队日常沟通",
      "德语或英语能力",
      "有SAP云解决方案经验者优先",
    ],
    tags: ["React", "Node.js", "Cloud", "Remote"],
    applicationUrl: "https://jobs.sap.com",
    postedDate: "2026-08-05",
    remoteFriendly: true,
    visaSponsorship: false,
    featured: true,
  },
  {
    id: "005",
    title: "Machine Learning Engineer - NLP",
    titleZh: "机器学习工程师 - 自然语言处理",
    company: "DeepL GmbH",
    field: "ai",
    location: "Cologne, Germany",
    locationCode: "de",
    languageLevel: "required",
    employmentType: "full-time",
    salaryRange: "€80,000 - €110,000",
    description: "Help us build the world's most accurate translation system. We are improving our Chinese-German and Chinese-English translation pairs and need ML engineers with strong Chinese language understanding.",
    descriptionZh: "帮助我们构建世界上最准确的翻译系统。我们正在改进中德和中英翻译对，需要具有扎实中文理解能力的ML工程师。",
    requirements: [
      "MSc or PhD in CS, Computational Linguistics, or related",
      "Strong background in NLP and transformer architectures",
      "Experience with multilingual models (mBERT, XLM-R, etc.)",
      "Native or near-native Chinese for model evaluation and data curation",
      "Python programming, PyTorch/JAX",
    ],
    requirementsZh: [
      "计算机科学、计算语言学或相关领域硕士或博士学位",
      "NLP和Transformer架构扎实背景",
      "多语言模型经验（mBERT, XLM-R等）",
      "母语或接近母语水平的中文，用于模型评估和数据策划",
      "Python编程，PyTorch/JAX",
    ],
    tags: ["NLP", "Transformers", "Translation", "PyTorch"],
    applicationUrl: "https://www.deepl.com/careers",
    postedDate: "2026-08-03",
    remoteFriendly: true,
    visaSponsorship: true,
    featured: true,
  },
  {
    id: "006",
    title: "Autonomous Driving Algorithm Engineer",
    titleZh: "自动驾驶算法工程师",
    company: "BMW Group",
    companyZh: "宝马集团",
    field: "ai",
    location: "Munich, Germany",
    locationCode: "de",
    languageLevel: "required",
    employmentType: "full-time",
    salaryRange: "€75,000 - €100,000",
    description: "Develop perception and planning algorithms for BMW's autonomous driving platform. Close collaboration with our China R&D center in Beijing requires Chinese language proficiency.",
    descriptionZh: "为宝马自动驾驶平台开发感知和规划算法。需要与我们位于北京的中国研发中心密切合作，要求中文能力。",
    requirements: [
      "MSc/PhD in CS, EE, or Robotics",
      "Experience in sensor fusion, perception, or planning",
      "C++ and Python proficiency",
      "Chinese (Mandarin) for collaboration with Beijing team",
      "Knowledge of ADAS standards (ISO 26262)",
    ],
    requirementsZh: [
      "计算机科学、电子工程或机器人学硕士/博士",
      "传感器融合、感知或规划经验",
      "C++和Python熟练",
      "中文普通话，用于与北京团队合作",
      "了解ADAS标准（ISO 26262）",
    ],
    tags: ["Autonomous Driving", "Perception", "C++", "Sensor Fusion"],
    applicationUrl: "https://www.bmwgroup.jobs",
    postedDate: "2026-07-30",
    remoteFriendly: false,
    visaSponsorship: true,
    featured: true,
  },
  {
    id: "007",
    title: "UAV Test & Integration Engineer",
    titleZh: "无人机测试与集成工程师",
    company: "Quantum-Systems GmbH",
    field: "drone",
    location: "Gilching, Germany",
    locationCode: "de",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€55,000 - €75,000",
    description: "Test and integrate UAV systems for surveying and mapping applications. We are expanding to the Chinese market and value team members who can communicate with Chinese partners and customers.",
    descriptionZh: "测试和集成用于测量和测绘应用的无人机系统。我们正在拓展中国市场，希望团队成员能够与中国合作伙伴和客户沟通。",
    requirements: [
      "Degree in Aerospace, EE, or related field",
      "Experience with UAV systems and flight testing",
      "Python and MATLAB skills",
      "Chinese language skills are a plus",
    ],
    requirementsZh: [
      "航空航天、电子工程或相关领域学位",
      "无人机系统和飞行测试经验",
      "Python和MATLAB技能",
      "中文语言能力是加分项",
    ],
    tags: ["UAV", "Testing", "Integration", "Surveying"],
    applicationUrl: "https://quantum-systems.de/careers",
    postedDate: "2026-07-22",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "008",
    title: "Software Engineer - China Platform",
    titleZh: "软件工程师 - 中国平台",
    company: "Zalando SE",
    field: "cs",
    location: "Berlin, Germany",
    locationCode: "de",
    languageLevel: "fluent",
    employmentType: "full-time",
    salaryRange: "€65,000 - €90,000",
    description: "Build and maintain our e-commerce platform features tailored for Chinese-speaking markets. This role involves working with internationalization, localization, and cross-border payment systems.",
    descriptionZh: "构建和维护专为中文市场定制的电子商务平台功能。此角色涉及国际化、本地化和跨境支付系统的工作。",
    requirements: [
      "BSc in Computer Science or equivalent",
      "3+ years Java/Kotlin or Python experience",
      "Fluent Chinese for content localization and QA",
      "Experience with i18n/l10n frameworks",
    ],
    requirementsZh: [
      "计算机科学学士或同等学历",
      "3年以上Java/Kotlin或Python经验",
      "流利中文，用于内容本地化和QA",
      "有i18n/l10n框架经验",
    ],
    tags: ["Java", "Kotlin", "E-commerce", "i18n"],
    applicationUrl: "https://jobs.zalando.com",
    postedDate: "2026-08-02",
    remoteFriendly: true,
    visaSponsorship: true,
  },
  {
    id: "009",
    title: "Robotics Perception Engineer",
    titleZh: "机器人感知工程师",
    company: "Festo AG & Co. KG",
    companyZh: "费斯托",
    field: "robotics",
    location: "Esslingen, Germany",
    locationCode: "de",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€65,000 - €85,000",
    description: "Develop perception algorithms for collaborative robots (cobots) used in industrial automation. We have a growing presence in China and value engineers who can support our Chinese customers.",
    descriptionZh: "开发用于工业自动化的协作机器人（cobot）感知算法。我们在中国的业务不断增长，希望工程师能够支持我们的中国客户。",
    requirements: [
      "MSc in Robotics, CS, or related",
      "Experience with 3D vision, point cloud processing (PCL)",
      "C++ and Python skills",
      "Chinese language skills are beneficial",
    ],
    requirementsZh: [
      "机器人、计算机科学或相关领域硕士学位",
      "3D视觉、点云处理（PCL）经验",
      "C++和Python技能",
      "中文语言能力有益",
    ],
    tags: ["Perception", "Cobots", "PCL", "Industrial"],
    applicationUrl: "https://www.festo.com/career",
    postedDate: "2026-07-20",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "010",
    title: "AI Product Manager - China Market",
    titleZh: "AI产品经理 - 中国市场",
    company: "Siemens AG",
    companyZh: "西门子",
    field: "ai",
    location: "Munich, Germany",
    locationCode: "de",
    languageLevel: "fluent",
    employmentType: "full-time",
    salaryRange: "€85,000 - €115,000",
    description: "Lead AI product strategy for the Chinese market within Siemens Digital Industries. Bridge European AI development with Chinese market needs, working closely with our Chengdu and Beijing teams.",
    descriptionZh: "在西门子数字化工业部门领导面向中国市场的AI产品战略。将欧洲AI开发与中国市场需求连接起来，与我们成都和北京团队密切合作。",
    requirements: [
      "MBA or MSc in CS/Engineering + business experience",
      "5+ years product management in AI/ML",
      "Fluent Chinese (Mandarin) and English",
      "Understanding of Chinese AI market and regulations",
      "Experience working with cross-cultural teams",
    ],
    requirementsZh: [
      "MBA或计算机科学/工程硕士+商业经验",
      "5年以上AI/ML产品管理经验",
      "流利中文（普通话）和英语",
      "了解中国AI市场和法规",
      "跨文化团队工作经验",
    ],
    tags: ["Product Management", "AI Strategy", "China Market", "Digital Industries"],
    applicationUrl: "https://www.siemens.com/careers",
    postedDate: "2026-08-04",
    remoteFriendly: true,
    visaSponsorship: true,
    featured: true,
  },
  {
    id: "011",
    title: "DevOps Engineer (Remote)",
    titleZh: "DevOps工程师（远程）",
    company: "Celonis SE",
    field: "remote",
    location: "Remote (DACH)",
    locationCode: "remote",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€70,000 - €95,000",
    description: "Manage cloud infrastructure and CI/CD pipelines for our process mining platform. We have a growing team in China and Chinese language skills help with cross-team collaboration.",
    descriptionZh: "为我们的流程挖掘平台管理云基础设施和CI/CD管道。我们在中国的团队不断壮大，中文语言能力有助于跨团队协作。",
    requirements: [
      "BSc in CS or equivalent",
      "3+ years DevOps experience (Kubernetes, Terraform, AWS/GCP)",
      "Python or Go programming",
      "Chinese language skills are a plus",
    ],
    requirementsZh: [
      "计算机科学学士或同等学历",
      "3年以上DevOps经验（Kubernetes, Terraform, AWS/GCP）",
      "Python或Go编程",
      "中文语言能力是加分项",
    ],
    tags: ["Kubernetes", "Terraform", "AWS", "Remote"],
    applicationUrl: "https://www.celonis.com/careers",
    postedDate: "2026-07-18",
    remoteFriendly: true,
    visaSponsorship: false,
  },
  {
    id: "012",
    title: "Embedded Software Engineer - Drone Navigation",
    titleZh: "嵌入式软件工程师 - 无人机导航",
    company: "Dronetech GmbH",
    field: "drone",
    location: "Vienna, Austria",
    locationCode: "at",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€55,000 - €75,000",
    description: "Develop embedded navigation software for agricultural drones. We are exploring the Chinese agricultural drone market and welcome engineers with Chinese language skills.",
    descriptionZh: "开发农业无人机的嵌入式导航软件。我们正在探索中国农业无人机市场，欢迎具有中文能力的工程师。",
    requirements: [
      "BSc/MSc in EE, CS, or Aerospace",
      "Experience with RTOS, embedded C/C++",
      "Knowledge of GPS/GNSS, IMU integration",
      "Chinese language is a plus for China market expansion",
    ],
    requirementsZh: [
      "电子工程、计算机科学或航空航天学士/硕士",
      "RTOS、嵌入式C/C++经验",
      "GPS/GNSS、IMU集成知识",
      "中文能力是加分项（用于中国市场拓展）",
    ],
    tags: ["Embedded", "RTOS", "Navigation", "Agriculture"],
    applicationUrl: "https://dronetech.at/careers",
    postedDate: "2026-07-15",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "013",
    title: "Data Scientist - Manufacturing AI",
    titleZh: "数据科学家 - 制造业AI",
    company: "Continental AG",
    companyZh: "大陆集团",
    field: "ai",
    location: "Regensburg, Germany",
    locationCode: "de",
    languageLevel: "required",
    employmentType: "full-time",
    salaryRange: "€70,000 - €95,000",
    description: "Apply machine learning to optimize manufacturing processes across Continental's global plants, with special focus on Chinese facilities. Chinese language proficiency required for on-site collaboration.",
    descriptionZh: "应用机器学习优化大陆集团全球工厂的制造流程，特别关注中国工厂。需要中文能力进行现场协作。",
    requirements: [
      "MSc in CS, Statistics, or Data Science",
      "3+ years experience with Python, scikit-learn, PyTorch",
      "Experience with time series analysis and anomaly detection",
      "Chinese (Mandarin) for collaboration with China plants",
      "Willingness to travel to China",
    ],
    requirementsZh: [
      "计算机科学、统计学或数据科学硕士",
      "3年以上Python、scikit-learn、PyTorch经验",
      "时间序列分析和异常检测经验",
      "中文普通话，用于与中国工厂协作",
      "愿意出差中国",
    ],
    tags: ["Data Science", "Manufacturing", "Python", "Anomaly Detection"],
    applicationUrl: "https://www.continental.com/careers",
    postedDate: "2026-07-28",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "014",
    title: "Computer Vision Researcher",
    titleZh: "计算机视觉研究员",
    company: "DFKI (German Research Center for AI)",
    companyZh: "德国人工智能研究中心",
    field: "ai",
    location: "Kaiserslautern, Germany",
    locationCode: "de",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€60,000 - €85,000",
    description: "Conduct applied research in computer vision and multimodal AI. We have joint research projects with Chinese universities and welcome Chinese-speaking researchers.",
    descriptionZh: "从事计算机视觉和多模态AI的应用研究。我们与中国高校有联合研究项目，欢迎中文研究人员。",
    requirements: [
      "PhD in CS or related field (or near completion)",
      "Strong publication record in CVPR, ICCV, ECCV or similar",
      "PyTorch/TensorFlow expertise",
      "Chinese language skills beneficial for research collaborations",
    ],
    requirementsZh: [
      "计算机科学或相关领域博士学位（或即将完成）",
      "在CVPR、ICCV、ECCV或类似会议有发表记录",
      "PyTorch/TensorFlow专业知识",
      "中文语言能力有利于研究合作",
    ],
    tags: ["Research", "Computer Vision", "Multimodal", "Academic"],
    applicationUrl: "https://www.dfki.de/career",
    postedDate: "2026-07-10",
    remoteFriendly: true,
    visaSponsorship: true,
  },
  {
    id: "015",
    title: "Backend Engineer - Cross-Border Platform",
    titleZh: "后端工程师 - 跨境平台",
    company: "Trade Republic GmbH",
    field: "cs",
    location: "Berlin, Germany",
    locationCode: "de",
    languageLevel: "required",
    employmentType: "full-time",
    salaryRange: "€75,000 - €100,000",
    description: "Build scalable backend systems for our fintech platform with a focus on cross-border transactions. We are expanding to serve Chinese-speaking users in Europe and need engineers who understand both European fintech regulations and Chinese user expectations.",
    descriptionZh: "为我们的金融科技平台构建可扩展的后端系统，重点关注跨境交易。我们正在扩展以服务欧洲的中文用户，需要既了解欧洲金融科技法规又了解中国用户期望的工程师。",
    requirements: [
      "BSc/MSc in CS or equivalent",
      "4+ years backend experience (Kotlin, Java, or Go)",
      "Experience with distributed systems and event-driven architecture",
      "Chinese (Mandarin) required for China-related features",
      "Knowledge of financial regulations",
    ],
    requirementsZh: [
      "计算机科学学士/硕士或同等学历",
      "4年以上后端经验（Kotlin、Java或Go）",
      "分布式系统和事件驱动架构经验",
      "中文普通话（用于中国相关功能）",
      "了解金融法规",
    ],
    tags: ["Backend", "Kotlin", "Fintech", "Distributed Systems"],
    applicationUrl: "https://careers.traderepublic.com",
    postedDate: "2026-08-06",
    remoteFriendly: true,
    visaSponsorship: true,
    featured: true,
  },
  {
    id: "016",
    title: "Control Systems Engineer - Robotics",
    titleZh: "控制系统工程师 - 机器人",
    company: "Beckhoff Automation GmbH",
    field: "robotics",
    location: "Verl, Germany",
    locationCode: "de",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€60,000 - €80,000",
    description: "Develop real-time control systems for industrial robots and automation equipment. Our China subsidiary is growing rapidly and Chinese language skills are highly valued.",
    descriptionZh: "为工业机器人和自动化设备开发实时控制系统。我们的中国子公司正在快速发展，中文能力受到高度重视。",
    requirements: [
      "MSc in EE, Robotics, or Control Engineering",
      "Experience with real-time systems and PLC programming",
      "C/C++ and IEC 61131-3 knowledge",
      "Chinese language skills are a plus",
    ],
    requirementsZh: [
      "电子工程、机器人或控制工程硕士",
      "实时系统和PLC编程经验",
      "C/C++和IEC 61131-3知识",
      "中文语言能力是加分项",
    ],
    tags: ["Real-time", "PLC", "Control Systems", "Automation"],
    applicationUrl: "https://www.beckhoff.com/career",
    postedDate: "2026-07-12",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "017",
    title: "NLP Engineer - Chinese Language Processing",
    titleZh: "NLP工程师 - 中文语言处理",
    company: "Hugging Face",
    field: "ai",
    location: "Remote (EU)",
    locationCode: "remote",
    languageLevel: "fluent",
    employmentType: "full-time",
    salaryRange: "€80,000 - €120,000",
    description: "Improve Chinese language model performance on the Hugging Face platform. Work on tokenization, model fine-tuning, and evaluation benchmarks specifically for Chinese NLP tasks. Fluent Chinese is essential.",
    descriptionZh: "提升Hugging Face平台上中文语言模型的性能。专门针对中文NLP任务进行分词、模型微调和评估基准工作。流利中文是必备条件。",
    requirements: [
      "MSc/PhD in CS, NLP, or Computational Linguistics",
      "Strong experience with transformer models and tokenization",
      "Fluent Chinese (Mandarin) for model evaluation and data curation",
      "Python, PyTorch expertise",
      "Open-source contribution experience preferred",
    ],
    requirementsZh: [
      "计算机科学、NLP或计算语言学硕士/博士",
      "Transformer模型和分词的丰富经验",
      "流利中文（普通话），用于模型评估和数据策划",
      "Python、PyTorch专业知识",
      "有开源贡献经验优先",
    ],
    tags: ["NLP", "Chinese", "Transformers", "Open Source"],
    applicationUrl: "https://huggingface.co/careers",
    postedDate: "2026-08-07",
    remoteFriendly: true,
    visaSponsorship: false,
    featured: true,
  },
  {
    id: "018",
    title: "Drone Software Developer",
    titleZh: "无人机软件开发者",
    company: "Atlas Dynamics",
    field: "drone",
    location: "Zurich, Switzerland",
    locationCode: "ch",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "CHF 90,000 - CHF 120,000",
    description: "Develop mission planning and fleet management software for fixed-wing drones. We are expanding to Asian markets and Chinese language skills help with partnerships.",
    descriptionZh: "为固定翼无人机开发任务规划和机队管理软件。我们正在拓展亚洲市场，中文能力有助于合作伙伴关系。",
    requirements: [
      "BSc/MSc in CS or Aerospace",
      "Experience with Go, Python, and REST APIs",
      "Knowledge of mapping/GIS systems",
      "Chinese language skills are a plus",
    ],
    requirementsZh: [
      "计算机科学或航空航天学士/硕士",
      "Go、Python和REST API经验",
      "地图/GIS系统知识",
      "中文语言能力是加分项",
    ],
    tags: ["Go", "GIS", "Mission Planning", "Fixed-Wing"],
    applicationUrl: "https://www.atlasdynamics.eu/careers",
    postedDate: "2026-07-08",
    remoteFriendly: true,
    visaSponsorship: true,
  },
  {
    id: "019",
    title: "Computer Vision Engineer - Medical Imaging",
    titleZh: "计算机视觉工程师 - 医学影像",
    company: "Fraunhofer IIS",
    companyZh: "弗劳恩霍夫研究所",
    field: "ai",
    location: "Erlangen, Germany",
    locationCode: "de",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€60,000 - €85,000",
    description: "Develop AI-based medical image analysis tools. We collaborate with Chinese hospitals and research institutions on medical AI projects.",
    descriptionZh: "开发基于AI的医学影像分析工具。我们与中国医院和研究机构在医学AI项目上合作。",
    requirements: [
      "MSc/PhD in CS, Biomedical Engineering, or related",
      "Experience with medical image processing (DICOM, 3D segmentation)",
      "PyTorch/TensorFlow and C++ skills",
      "Chinese language skills beneficial for China collaborations",
    ],
    requirementsZh: [
      "计算机科学、生物医学工程或相关领域硕士/博士",
      "医学影像处理经验（DICOM, 3D分割）",
      "PyTorch/TensorFlow和C++技能",
      "中文能力有利于中国合作",
    ],
    tags: ["Medical Imaging", "DICOM", "Segmentation", "Research"],
    applicationUrl: "https://www.iis.fraunhofer.de/careers",
    postedDate: "2026-07-05",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "020",
    title: "Frontend Developer - China Localization",
    titleZh: "前端开发工程师 - 中国本地化",
    company: "NIO Munich",
    companyZh: "蔚来汽车慕尼黑",
    field: "cs",
    location: "Munich, Germany",
    locationCode: "de",
    languageLevel: "fluent",
    employmentType: "full-time",
    salaryRange: "€65,000 - €90,000",
    description: "Build and localize the NIO app and vehicle infotainment interface for the European market, working closely with the Shanghai headquarters. Fluent Chinese is essential for daily communication.",
    descriptionZh: "为欧洲市场构建和本地化NIO应用程序和车载信息娱乐界面，与上海总部密切合作。流利中文是日常沟通的必备条件。",
    requirements: [
      "BSc in CS or equivalent",
      "3+ years React/Vue.js experience",
      "Fluent Chinese (Mandarin) for HQ communication",
      "Experience with i18n frameworks",
      "UI/UX sensibility",
    ],
    requirementsZh: [
      "计算机科学学士或同等学历",
      "3年以上React/Vue.js经验",
      "流利中文普通话，用于与总部沟通",
      "有i18n框架经验",
      "UI/UX敏感度",
    ],
    tags: ["React", "Vue.js", "Infotainment", "Localization"],
    applicationUrl: "https://nio.com/careers",
    postedDate: "2026-08-01",
    remoteFriendly: false,
    visaSponsorship: true,
    featured: true,
  },
  {
    id: "021",
    title: "Autonomous Systems Researcher",
    titleZh: "自主系统研究员",
    company: "ETH Zurich",
    field: "robotics",
    location: "Zurich, Switzerland",
    locationCode: "ch",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "CHF 95,000 - CHF 130,000",
    description: "Conduct research on autonomous navigation and decision-making for mobile robots. We have joint projects with Tsinghua University and value Chinese-speaking researchers.",
    descriptionZh: "研究移动机器人的自主导航和决策。我们与清华大学有联合项目，重视中文研究人员。",
    requirements: [
      "PhD in Robotics, CS, or related",
      "Strong publication record (ICRA, IROS, RSS)",
      "Experience with SLAM, path planning, or reinforcement learning",
      "Chinese language skills beneficial",
    ],
    requirementsZh: [
      "机器人、计算机科学或相关领域博士",
      "在ICRA、IROS、RSS有发表记录",
      "SLAM、路径规划或强化学习经验",
      "中文能力有益",
    ],
    tags: ["Research", "SLAM", "Reinforcement Learning", "Academic"],
    applicationUrl: "https://ethz.ch/careers",
    postedDate: "2026-07-03",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "022",
    title: "Cloud Solutions Architect - China Region",
    titleZh: "云解决方案架构师 - 中国区",
    company: "Huawei Technologies Düsseldorf",
    companyZh: "华为杜塞尔多夫",
    field: "cs",
    location: "Düsseldorf, Germany",
    locationCode: "de",
    languageLevel: "fluent",
    employmentType: "full-time",
    salaryRange: "€80,000 - €110,000",
    description: "Design cloud architecture solutions for European enterprise customers with China operations. Bridge Huawei cloud services between EU and China. Fluent Chinese required.",
    descriptionZh: "为有中国业务的欧洲企业客户设计云架构解决方案。在欧盟和中国之间架起华为云服务桥梁。需要流利的中文。",
    requirements: [
      "BSc/MSc in CS or equivalent",
      "5+ years cloud architecture experience (AWS/Azure/Huawei Cloud)",
      "Fluent Chinese (Mandarin) and English",
      "Kubernetes, microservices, and DevOps expertise",
      "EU work authorization",
    ],
    requirementsZh: [
      "计算机科学学士/硕士或同等学历",
      "5年以上云架构经验（AWS/Azure/华为云）",
      "流利中文（普通话）和英语",
      "Kubernetes、微服务和DevOps专业知识",
      "欧盟工作许可",
    ],
    tags: ["Cloud", "Kubernetes", "Architecture", "Huawei Cloud"],
    applicationUrl: "https://career.huawei.com",
    postedDate: "2026-08-05",
    remoteFriendly: true,
    visaSponsorship: false,
    featured: true,
  },
  {
    id: "023",
    title: "SLAM Engineer for Mobile Robots",
    titleZh: "移动机器人SLAM工程师",
    company: "Pilz GmbH",
    field: "robotics",
    location: "Ostfildern, Germany",
    locationCode: "de",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€60,000 - €80,000",
    description: "Develop SLAM and navigation algorithms for autonomous mobile robots (AMRs) used in industrial environments. We are expanding to China and value engineers with Chinese market understanding.",
    descriptionZh: "开发用于工业环境的自主移动机器人（AMR）的SLAM和导航算法。我们正在拓展中国市场，重视对中国市场有了解的工程师。",
    requirements: [
      "MSc in Robotics, CS, or related",
      "Experience with SLAM (Cartographer, ORB-SLAM, etc.)",
      "C++ and Python proficiency",
      "ROS/ROS2 experience",
      "Chinese language skills are a plus",
    ],
    requirementsZh: [
      "机器人、计算机科学或相关领域硕士",
      "SLAM经验（Cartographer, ORB-SLAM等）",
      "C++和Python熟练",
      "ROS/ROS2经验",
      "中文语言能力是加分项",
    ],
    tags: ["SLAM", "AMR", "ROS2", "Navigation"],
    applicationUrl: "https://www.pilz.com/careers",
    postedDate: "2026-07-14",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "024",
    title: "AI Safety & Reliability Engineer",
    titleZh: "AI安全与可靠性工程师",
    company: "TÜV SÜD",
    companyZh: "南德意志检验",
    field: "ai",
    location: "Munich, Germany",
    locationCode: "de",
    languageLevel: "required",
    employmentType: "full-time",
    salaryRange: "€70,000 - €95,000",
    description: "Develop testing and certification frameworks for AI systems in automotive and industrial applications. We certify AI products for the Chinese market and need engineers who understand both EU and China AI regulations.",
    descriptionZh: "开发汽车和工业应用中AI系统的测试和认证框架。我们为中国市场的AI产品提供认证，需要同时了解欧盟和中国AI法规的工程师。",
    requirements: [
      "MSc in CS, EE, or related",
      "Experience with AI/ML testing and validation",
      "Knowledge of ISO 26262, ISO 21448 (SOTIF)",
      "Chinese (Mandarin) for China market certification projects",
      "Understanding of Chinese AI regulations",
    ],
    requirementsZh: [
      "计算机科学、电子工程或相关领域硕士",
      "AI/ML测试和验证经验",
      "了解ISO 26262、ISO 21448（SOTIF）",
      "中文普通话，用于中国市场认证项目",
      "了解中国AI法规",
    ],
    tags: ["AI Safety", "Certification", "ISO 26262", "Automotive"],
    applicationUrl: "https://www.tuvsud.com/careers",
    postedDate: "2026-07-19",
    remoteFriendly: true,
    visaSponsorship: true,
  },
  {
    id: "025",
    title: "Software Engineering Intern - Drone AI",
    titleZh: "软件工程实习生 - 无人机AI",
    company: "Max Planck Institute",
    field: "drone",
    location: "Tübingen, Germany",
    locationCode: "de",
    languageLevel: "nice-to-have",
    employmentType: "internship",
    salaryRange: "€2,000 - €2,500/month",
    description: "Internship position developing AI-powered swarm intelligence for drone swarms. We collaborate with Chinese research institutes and welcome Chinese-speaking interns.",
    descriptionZh: "开发AI驱动的无人机集群智能的实习职位。我们与中国研究机构合作，欢迎中文实习生。",
    requirements: [
      "Enrolled in CS, AI, or Robotics MSc program",
      "Python and PyTorch experience",
      "Interest in multi-agent systems and swarm intelligence",
      "Chinese language skills are a plus",
      "6-month minimum commitment",
    ],
    requirementsZh: [
      "在读计算机科学、AI或机器人硕士课程",
      "Python和PyTorch经验",
      "对多智能体系统和集群智能感兴趣",
      "中文语言能力是加分项",
      "至少6个月承诺",
    ],
    tags: ["Internship", "Swarm", "Research", "Multi-Agent"],
    applicationUrl: "https://www.is.mpg.de/careers",
    postedDate: "2026-07-01",
    remoteFriendly: false,
    visaSponsorship: false,
  },
  {
    id: "026",
    title: "Site Reliability Engineer (Remote)",
    titleZh: "站点可靠性工程师（远程）",
    company: "GitLab GmbH",
    field: "remote",
    location: "Remote (Germany)",
    locationCode: "remote",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€75,000 - €100,000",
    description: "Join our all-remote SRE team to maintain and scale GitLab's infrastructure. We have growing adoption in China and Chinese language skills help with community support and documentation.",
    descriptionZh: "加入我们全远程的SRE团队，维护和扩展GitLab的基础设施。我们在中国的采用量不断增长，中文能力有助于社区支持和文档。",
    requirements: [
      "BSc in CS or equivalent",
      "3+ years SRE or DevOps experience",
      "Ruby, Go, and Kubernetes expertise",
      "Chinese language skills are a plus",
    ],
    requirementsZh: [
      "计算机科学学士或同等学历",
      "3年以上SRE或DevOps经验",
      "Ruby、Go和Kubernetes专业知识",
      "中文语言能力是加分项",
    ],
    tags: ["SRE", "Kubernetes", "Go", "Remote"],
    applicationUrl: "https://about.gitlab.com/jobs",
    postedDate: "2026-07-25",
    remoteFriendly: true,
    visaSponsorship: false,
  },
  {
    id: "027",
    title: "Reinforcement Learning Engineer",
    titleZh: "强化学习工程师",
    company: "BMW Autonomous Driving",
    companyZh: "宝马自动驾驶",
    field: "ai",
    location: "Munich, Germany",
    locationCode: "de",
    languageLevel: "required",
    employmentType: "full-time",
    salaryRange: "€80,000 - €105,000",
    description: "Develop RL-based decision-making systems for autonomous driving. Close collaboration with BMW's China tech center in Shanghai requires Chinese language proficiency.",
    descriptionZh: "开发基于强化学习的自动驾驶决策系统。需要与宝马在上海的中国技术中心密切合作，要求中文能力。",
    requirements: [
      "MSc/PhD in CS, EE, or Robotics",
      "Strong background in reinforcement learning (PPO, SAC, etc.)",
      "Experience with simulation environments (CARLA, SUMO)",
      "Chinese (Mandarin) for Shanghai team collaboration",
      "Python and C++ proficiency",
    ],
    requirementsZh: [
      "计算机科学、电子工程或机器人学硕士/博士",
      "强化学习扎实背景（PPO, SAC等）",
      "仿真环境经验（CARLA, SUMO）",
      "中文普通话，用于与上海团队合作",
      "Python和C++熟练",
    ],
    tags: ["Reinforcement Learning", "CARLA", "Autonomous Driving", "C++"],
    applicationUrl: "https://www.bmwgroup.jobs",
    postedDate: "2026-07-29",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "028",
    title: "Edge Computing Engineer for Robotics",
    titleZh: "机器人边缘计算工程师",
    company: "IFM Electronic GmbH",
    field: "robotics",
    location: "Essen, Germany",
    locationCode: "de",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€60,000 - €80,000",
    description: "Develop edge AI solutions for industrial sensors and robotics applications. Our China business is growing and Chinese language skills are valued for customer projects.",
    descriptionZh: "为工业传感器和机器人应用开发边缘AI解决方案。我们在中国的业务不断增长，中文能力在客户项目中受到重视。",
    requirements: [
      "BSc/MSc in CS, EE, or related",
      "Experience with edge computing (NVIDIA Jetson, ARM)",
      "Python, C++ and embedded Linux",
      "TensorRT or ONNX runtime experience",
      "Chinese language skills are a plus",
    ],
    requirementsZh: [
      "计算机科学、电子工程或相关领域学士/硕士",
      "边缘计算经验（NVIDIA Jetson, ARM）",
      "Python、C++和嵌入式Linux",
      "TensorRT或ONNX Runtime经验",
      "中文语言能力是加分项",
    ],
    tags: ["Edge AI", "Jetson", "Embedded", "Sensors"],
    applicationUrl: "https://www.ifm.com/careers",
    postedDate: "2026-07-16",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "029",
    title: "Mobile Developer - Chinese App Market",
    titleZh: "移动开发工程师 - 中国应用市场",
    company: "BYD Europe",
    companyZh: "比亚迪欧洲",
    field: "cs",
    location: "Stuttgart, Germany",
    locationCode: "de",
    languageLevel: "fluent",
    employmentType: "full-time",
    salaryRange: "€65,000 - €90,000",
    description: "Develop mobile apps for BYD's European EV ecosystem, integrating with Chinese backend services and WeChat mini-programs. Fluent Chinese required for HQ coordination.",
    descriptionZh: "为比亚迪欧洲电动汽车生态系统开发移动应用程序，集成中国后端服务和微信小程序。需要流利中文用于总部协调。",
    requirements: [
      "BSc in CS or equivalent",
      "3+ years iOS (Swift) or Android (Kotlin) development",
      "Fluent Chinese (Mandarin) for HQ communication",
      "Experience with WeChat Mini Programs is a plus",
      "Understanding of Chinese app ecosystem",
    ],
    requirementsZh: [
      "计算机科学学士或同等学历",
      "3年以上iOS (Swift)或Android (Kotlin)开发",
      "流利中文普通话，用于与总部沟通",
      "有微信小程序经验优先",
      "了解中国应用生态系统",
    ],
    tags: ["iOS", "Android", "WeChat", "EV"],
    applicationUrl: "https://www.bydeurope.com/careers",
    postedDate: "2026-08-03",
    remoteFriendly: false,
    visaSponsorship: true,
    featured: true,
  },
  {
    id: "030",
    title: "Perception Engineer - Autonomous Drones",
    titleZh: "感知工程师 - 自动驾驶无人机",
    company: "FlyNow Aviation GmbH",
    field: "drone",
    location: "Salzburg, Austria",
    locationCode: "at",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€55,000 - €75,000",
    description: "Develop perception systems for autonomous passenger and cargo drones. We are targeting the Asian market including China and value team members with Chinese market knowledge.",
    descriptionZh: "开发用于自主客运和货运无人机的感知系统。我们正瞄准包括中国在内的亚洲市场，重视具有中国市场知识的团队成员。",
    requirements: [
      "MSc in CS, Aerospace, or related",
      "Experience with 3D perception, LiDAR, and camera fusion",
      "C++ and Python proficiency",
      "Chinese language skills are a plus",
    ],
    requirementsZh: [
      "计算机科学、航空航天或相关领域硕士",
      "3D感知、LiDAR和摄像头融合经验",
      "C++和Python熟练",
      "中文语言能力是加分项",
    ],
    tags: ["Perception", "LiDAR", "UAV", "Autonomous"],
    applicationUrl: "https://flynow.aero/careers",
    postedDate: "2026-07-06",
    remoteFriendly: false,
    visaSponsorship: true,
  },
  {
    id: "031",
    title: "AI Ethics & Policy Researcher",
    titleZh: "AI伦理与政策研究员",
    company: "Max Planck Institute",
    field: "ai",
    location: "Munich, Germany",
    locationCode: "de",
    languageLevel: "required",
    employmentType: "full-time",
    salaryRange: "€65,000 - €85,000",
    description: "Research AI governance frameworks comparing EU AI Act with Chinese AI regulations. Publish policy recommendations and advise on cross-border AI cooperation. Chinese language proficiency essential for policy research.",
    descriptionZh: "研究比较欧盟AI法案与中国AI法规的AI治理框架。发布政策建议并就跨境AI合作提供建议。中文能力对政策研究至关重要。",
    requirements: [
      "PhD in CS, Law, Philosophy, or STS",
      "Knowledge of EU AI Act and Chinese AI regulations",
      "Chinese (Mandarin) for reading Chinese policy documents",
      "Strong academic writing skills",
    ],
    requirementsZh: [
      "计算机科学、法律、哲学或科技与社会博士",
      "了解欧盟AI法案和中国AI法规",
      "中文普通话，用于阅读中文政策文件",
      "扎实的学术写作能力",
    ],
    tags: ["AI Ethics", "Policy", "Governance", "Research"],
    applicationUrl: "https://www.is.mpg.de/careers",
    postedDate: "2026-07-04",
    remoteFriendly: true,
    visaSponsorship: true,
  },
  {
    id: "032",
    title: "Computer Graphics Engineer - VR/Robotics",
    titleZh: "计算机图形工程师 - VR/机器人",
    company: "Volocopter GmbH",
    field: "robotics",
    location: "Bruchsal, Germany",
    locationCode: "de",
    languageLevel: "nice-to-have",
    employmentType: "full-time",
    salaryRange: "€65,000 - €85,000",
    description: "Develop 3D visualization and simulation tools for eVTOL aircraft flight planning. We are expanding to China and value engineers with Chinese language skills.",
    descriptionZh: "为eVTOL飞行器飞行规划开发3D可视化和仿真工具。我们正在拓展中国市场，重视具有中文能力的工程师。",
    requirements: [
      "BSc/MSc in CS or related",
      "Experience with Three.js, WebGL, or Unity",
      "C++ and Python skills",
      "Chinese language skills are a plus",
    ],
    requirementsZh: [
      "计算机科学或相关领域学士/硕士",
      "Three.js、WebGL或Unity经验",
      "C++和Python技能",
      "中文语言能力是加分项",
    ],
    tags: ["VR", "3D Visualization", "eVTOL", "Unity"],
    applicationUrl: "https://www.volocopter.com/careers",
    postedDate: "2026-07-11",
    remoteFriendly: true,
    visaSponsorship: true,
  },
];
