import type { ScraperSource } from "./types";

export const scraperSources: ScraperSource[] = [
  {
    id: "stepstone-chinese-de",
    name: "StepStone DE - Chinese Keyword",
    nameZh: "StepStone 德国 - 中文关键词",
    type: "rss",
    url: "https://www.stepstone.de/jobs/chinesisch/in-deutschland/rss",
    enabled: true,
    keywords: ["chinesisch", "chinese", "mandarin", "中文"],
    defaultField: undefined,
    defaultLocationCode: "de",
  },
  {
    id: "indeed-chinese-de",
    name: "Indeed DE - Chinese Keyword",
    nameZh: "Indeed 德国 - 中文关键词",
    type: "html",
    url: "https://de.indeed.com/jobs?q=chinesisch&l=Deutschland",
    enabled: true,
    jsRendered: true,
    puppeteerOptions: {
      waitForSelector: ".job_seen_bea, [data-jk]",
      waitTimeout: 10000,
      scrollDelay: 2000,
      extraWaitMs: 3000,
    },
    keywords: ["chinesisch", "chinese", "mandarin", "中文"],
    selectors: {
      jobCard: ".job_seen_bea, .result, [data-jk]",
      title: "h2.jobTitle a, h2 a span, [data-jk] h2 a",
      company: ".companyName, [data-jk] .companyName",
      location: ".companyLocation, [data-jk] .companyLocation",
      link: "h2.jobTitle a, h2 a, a.jobtitle",
      description: ".job-snippet, .summary",
    },
    defaultLocationCode: "de",
  },
  {
    id: "bosch-careers-china",
    name: "Bosch Careers - China/AI",
    nameZh: "博世招聘 - 中国/AI",
    type: "html",
    url: "https://www.bosch.de/de/karriere/job-suche/?country=DE&keyword=chinese",
    enabled: false,
    jsRendered: true,
    puppeteerOptions: {
      waitForSelector: ".job-item, .job-result, .posting",
      waitTimeout: 12000,
      scrollDelay: 2000,
      extraWaitMs: 2000,
    },
    keywords: ["chinese", "chinesisch", "china", "mandarin"],
    selectors: {
      jobCard: ".job-item, .job-result, .posting",
      title: ".job-title, h3, h2",
      company: "Robert Bosch",
      location: ".job-location, .location",
      link: "a.job-link, a",
    },
    defaultField: "ai",
    defaultLocationCode: "de",
  },
  {
    id: "linkedin-chinese-de",
    name: "LinkedIn - Chinese Jobs Germany",
    nameZh: "LinkedIn - 德国中文职位",
    type: "html",
    url: "https://www.linkedin.com/jobs/search/?keywords=chinese%20language&location=Germany",
    enabled: false,
    jsRendered: true,
    puppeteerOptions: {
      waitForSelector: ".jobs-search__results-list li, .job-search-card",
      waitTimeout: 15000,
      scrollDelay: 3000,
      extraWaitMs: 3000,
    },
    keywords: ["chinese", "chinesisch", "mandarin", "中文"],
    selectors: {
      jobCard: ".jobs-search__results-list li, .job-search-card",
      title: ".base-search-card__title",
      company: ".base-search-card__subtitle",
      location: ".job-search-card__location",
      link: "a.base-card__full-link",
    },
    defaultLocationCode: "de",
  },
  {
    id: "xing-chinese-de",
    name: "XING Jobs - Chinese Keyword",
    nameZh: "XING 职位 - 中文关键词",
    type: "html",
    url: "https://www.xing.com/jobs/search?q=chinesisch&location=Deutschland",
    enabled: false,
    jsRendered: true,
    puppeteerOptions: {
      waitForSelector: "[data-testid='job-posting-card'], .job-posting",
      waitTimeout: 12000,
      scrollDelay: 2000,
      extraWaitMs: 2000,
    },
    keywords: ["chinesisch", "chinese", "mandarin"],
    selectors: {
      jobCard: "[data-testid='job-posting-card'], .job-posting",
      title: "h3 a, h4 a, [data-testid='job-title']",
      company: "[data-testid='company-name'], .company-name",
      location: "[data-testid='job-location'], .location",
      link: "h3 a, h4 a, a[href*='/jobs/']",
    },
    defaultLocationCode: "de",
  },
  {
    id: "sapprosoftmoms-china",
    name: "SAP Careers - Chinese",
    nameZh: "SAP 招聘 - 中文",
    type: "html",
    url: "https://jobs.sap.com/search/?q=chinese&locationsearch=Germany",
    enabled: false,
    keywords: ["chinese", "chinesisch", "mandarin", "china"],
    selectors: {
      jobCard: ".job-result, .search-result",
      title: ".job-title, h3 a",
      company: "SAP SE",
      location: ".job-location",
      link: "h3 a, a.job-link",
    },
    defaultField: "cs",
    defaultLocationCode: "de",
  },
  {
    id: "huawei-europe-china",
    name: "Huawei Europe Careers",
    nameZh: "华为欧洲招聘",
    type: "html",
    url: "https://career.huawei.com/reccampportal/portal5/campus-recruitment.html?jobType=2&language=en",
    enabled: false,
    jsRendered: true,
    puppeteerOptions: {
      waitForSelector: ".job-item, .position-item",
      waitTimeout: 15000,
      scrollDelay: 3000,
      extraWaitMs: 3000,
    },
    keywords: ["chinese", "mandarin", "中文", "china"],
    selectors: {
      jobCard: ".job-item, .position-item",
      title: ".job-title, .position-name",
      company: "Huawei",
      location: ".job-location",
      link: "a.job-link, a",
    },
    defaultLocationCode: "de",
  },
  {
    id: "dfki-ai-china",
    name: "DFKI - AI Research",
    nameZh: "德国人工智能研究中心",
    type: "html",
    url: "https://www.dfki.de/en/jobs-and-careers/",
    enabled: false,
    keywords: ["chinese", "china", "ai", "machine learning", "robotics"],
    selectors: {
      jobCard: ".job-item, .vacancy, .position",
      title: "h3, h4, .job-title",
      company: "DFKI",
      location: ".location",
      link: "a",
    },
    defaultField: "ai",
    defaultLocationCode: "de",
  },
  {
    id: "fraunhofer-ai-china",
    name: "Fraunhofer - AI/Robotics",
    nameZh: "弗劳恩霍夫 - AI/机器人",
    type: "html",
    url: "https://www.fraunhofer.de/en/jobs.html",
    enabled: false,
    keywords: ["chinese", "china", "ai", "robotics", "machine learning"],
    selectors: {
      jobCard: ".job-item, .vacancy, .search-result",
      title: "h3 a, h4 a, .job-title",
      company: "Fraunhofer",
      location: ".location",
      link: "a",
    },
    defaultField: "ai",
    defaultLocationCode: "de",
  },
  {
    id: "make-it-in-germany",
    name: "Make it in Germany - IT/Chinese",
    nameZh: "在德国工作 - IT/中文",
    type: "html",
    url: "https://www.make-it-in-germany.com/en/working-in-germany/job-listings",
    enabled: false,
    keywords: ["chinese", "chinesisch", "ai", "robotics", "software"],
    selectors: {
      jobCard: ".job-item, .job-result",
      title: "h3 a, h4 a, .job-title",
      company: ".company",
      location: ".location",
      link: "a",
    },
    defaultLocationCode: "de",
  },
  {
    id: "machinelearningjobs-de",
    name: "MachineLearningJobs.de",
    nameZh: "机器学习职位德国",
    type: "html",
    url: "https://machinelearningjobs.de/jobs/",
    enabled: false,
    keywords: ["chinese", "chinesisch", "mandarin", "china"],
    selectors: {
      jobCard: ".job-listing, .job-card, article",
      title: "h2 a, h3 a, .job-title",
      company: ".company-name, .employer",
      location: ".location",
      link: "h2 a, h3 a, a.job-link",
    },
    defaultField: "ai",
    defaultLocationCode: "de",
  },
  {
    id: "remoteok-chinese",
    name: "RemoteOK - Chinese",
    nameZh: "RemoteOK - 中文",
    type: "json-api",
    url: "https://remoteok.com/api?tags=chinese",
    enabled: true,
    keywords: ["chinese", "mandarin", "中文"],
    defaultField: "remote",
    defaultLocationCode: "remote",
  },
  {
    id: "dronejobs-de",
    name: "DroneJobs.de",
    nameZh: "无人机职位德国",
    type: "html",
    url: "https://www.dronejobs.de/jobs/",
    enabled: false,
    keywords: ["chinese", "chinesisch", "china"],
    selectors: {
      jobCard: ".job-item, .job-card, article",
      title: "h2 a, h3 a, .job-title",
      company: ".company-name",
      location: ".location",
      link: "h2 a, h3 a",
    },
    defaultField: "drone",
    defaultLocationCode: "de",
  },
];

export function getEnabledSources(): ScraperSource[] {
  return scraperSources.filter((s) => s.enabled);
}

export function getSourceById(id: string): ScraperSource | undefined {
  return scraperSources.find((s) => s.id === id);
}
